# Site settings
title: geteventflow.net
email: r@smus.nu
description: >
  Easy to use async/await first CRQS+ES framework
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geteventflow.net"

# Build settings
markdown: kramdown
